{
 "title": "Avalanche Project",
 "tags": [ "project" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Relayer Balance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ETH Relayer balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ETH" }
   ],
   "targets": [
    {
     "alias": "balance ETH",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_getbalance" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "relayer" }
     ]
    }
   ]
  },
  {
   "title": "AVAX Relayer balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "AVAX" }
   ],
   "targets": [
    {
     "alias": "balance AVAX",
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_getbalance" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "relayer" }
     ]
    }
   ]
  },
  {
   "title": "Relayer Balance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ETH",
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_getbalance" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "relayer" }
     ]
    },
    {
     "alias": "AVAX",
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_getbalance" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "relayer" }
     ]
    }
   ]
  },
  {
   "title": "Avalanche Staked AVAX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "AVAX" }
   ],
   "targets": [
    {
     "alias": "staked AVAX",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "staked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" }
     ]
    }
   ]
  },
  { "title": "Bridge Balance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "ETH Bridge balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ETH" }
   ],
   "targets": [
    {
     "alias": "balance ETH",
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_getbalance" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "bridge" }
     ]
    }
   ]
  },
  {
   "title": "AVAX Bridge balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "AVAX" }
   ],
   "targets": [
    {
     "alias": "balance AVAX",
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_getbalance" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "bridge" }
     ]
    }
   ]
  },
  {
   "title": "Bridge Balance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ETH",
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "bridge" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_getbalance" }
     ]
    },
    {
     "alias": "AVAX",
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_getbalance" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "bridge" }
     ]
    }
   ]
  },
  {
   "title": "Pending Bridge TXs count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TXs",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" }
     ]
    }
   ]
  },
  {
   "title": "ETH Production Node (openethereum)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "openethereum prod node CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 +100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" }
     ]
    }
   ]
  },
  {
   "title": "openethereum prod node Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" }
     ]
    }
   ]
  },
  {
   "title": "openethereum prod node Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "/ volume",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "/data volume",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/data" }
     ]
    }
   ]
  },
  {
   "title": "openethereum prod node - RPC response code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" }
     ]
    }
   ]
  },
  {
   "title": "OE prod node Highest Block Number",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_blocknumber" }
     ]
    }
   ]
  },
  {
   "title": "openethereum prod node Highest Block Number growth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "blocks per minute",
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_blocknumber" }
     ]
    }
   ]
  },
  {
   "title": "openethereum prod node eth_syncing",
   "type": "graph",
   "description": "0 - eth_syncing returns \"false\"\n1 - eth_suncing returns some other response",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "eth-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_syncing" }
     ]
    }
   ]
  },
  { "title": "ETH Production Node (geth)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "geth prod node CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "geth-prod-node" }
     ]
    }
   ]
  },
  {
   "title": "geth prod node Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "geth-prod-node" }
     ]
    }
   ]
  },
  {
   "title": "geth prod node Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "/ volume",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "geth-prod-node" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "/data volume",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "geth-prod-node" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/data" }
     ]
    }
   ]
  },
  {
   "title": "geth prod node RPC response code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "geth-prod-node" }
     ]
    }
   ]
  },
  {
   "title": "geth prod node Highest Block Number",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "geth-prod-node" }
     ]
    }
   ]
  },
  {
   "title": "geth prod node Highest Block Number growth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "blocks per minute",
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "geth-prod-node" }
     ]
    }
   ]
  },
  {
   "title": "geth prod node eth_syncing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "eth_syncing. 0 - false, 1 - true",
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "geth-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_syncing" }
     ]
    }
   ]
  },
  {
   "title": "Avalanche Production Node (docker + avalanchego)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "Avalanche prod node CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *-1+ 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" }
     ]
    }
   ]
  },
  {
   "title": "Avalanche prod node Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" }
     ]
    }
   ]
  },
  {
   "title": "Avalanche prod node Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "/ volume",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "/data volume",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/data" }
     ]
    }
   ]
  },
  {
   "title": "Avalanche prod node Health API",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "healthy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" },
      { "condition": "AND", "key": "api_endpoint", "operator": "=", "value": "/ext/health" }
     ]
    }
   ]
  },
  {
   "title": "Avalanche prod node Highest Block",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_blocknumber" }
     ]
    }
   ]
  },
  {
   "title": "Avalanche prod node Block Number Growth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "blocks per minute",
     "measurement": "http",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_blocknumber" }
     ]
    }
   ]
  },
  {
   "title": "Avalanche prod node Container is Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "avalanche-prod-node" }
     ]
    }
   ]
  },
  { "title": "Relayer Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "relayer prod CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "prod-relayer" }
     ]
    }
   ]
  },
  {
   "title": "relayer prod Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 62 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "prod-relayer" }
     ]
    }
   ]
  },
  {
   "title": "relayer prod Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "prod-relayer" }
     ]
    }
   ]
  },
  {
   "title": "relayer prod Containers Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "containers running",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "prod-relayer" }
     ]
    }
   ]
  },
  {
   "title": "relayer prod Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "measurement": "docker_log",
     "select": [
      [
       { "params": [ "message" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "prod-relayer" }
     ]
    }
   ]
  }
 ]
}