{
 "title": "Meter Project",
 "tags": [ "project" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Balances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ETH balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "yaxes": [
    { "format": "ETH" }
   ],
   "targets": [
    {
     "alias": "relayer",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter-relayer" },
      { "condition": "AND", "key": "blockchain", "operator": "=", "value": "ethereum" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "relayer" }
     ]
    },
    {
     "alias": "bridge",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter-relayer" },
      { "condition": "AND", "key": "blockchain", "operator": "=", "value": "ethereum" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "bridge" }
     ]
    }
   ]
  },
  {
   "title": "MTR balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MTR" } },
   "yaxes": [
    { "format": "MTR" }
   ],
   "targets": [
    {
     "alias": "relayer",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter-relayer" },
      { "condition": "AND", "key": "blockchain", "operator": "=", "value": "meter" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "relayer" }
     ]
    },
    {
     "alias": "bridge",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter-relayer" },
      { "condition": "AND", "key": "blockchain", "operator": "=", "value": "meter" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "bridge" }
     ]
    }
   ]
  },
  {
   "title": "BNB balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "BNB" } },
   "yaxes": [
    { "format": "BNB" }
   ],
   "targets": [
    {
     "alias": "relayer",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter-relayer" },
      { "condition": "AND", "key": "blockchain", "operator": "=", "value": "bsc" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "relayer" }
     ]
    },
    {
     "alias": "bridge",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter-relayer" },
      { "condition": "AND", "key": "blockchain", "operator": "=", "value": "bsc" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "bridge" }
     ]
    }
   ]
  },
  { "title": "Relayer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "meter relayer CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "cpu utilization",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 +100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter-relayer" }
     ]
    }
   ]
  },
  {
   "title": "meter relayer Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter-relayer" }
     ]
    }
   ]
  },
  {
   "title": "meter relayer Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "/ volume",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter-relayer" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "meter relayer - container status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Containers running",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter-relayer" }
     ]
    }
   ]
  },
  {
   "title": "meter relayer Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "measurement": "docker_log",
     "select": [
      [
       { "params": [ "message" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter-relayer" }
     ]
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "meter node CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "cpu utilization",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 +100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter" }
     ]
    }
   ]
  },
  {
   "title": "meter node Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter" }
     ]
    }
   ]
  },
  {
   "title": "meter node Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "/ volume",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "/data volume",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/data" }
     ]
    }
   ]
  },
  {
   "title": "meter node - container status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Containers running",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "query": "SELECT mean(\"n_containers_running\") FROM \"docker\" WHERE (\"host\" = 'meter') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter" }
     ]
    }
   ]
  },
  {
   "title": "meter node Highest Block Number",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "number" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter" },
      { "condition": "AND", "key": "api_endpoint", "operator": "=", "value": "blocks" }
     ]
    }
   ]
  },
  {
   "title": "meter node Highest Block Number growth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "blocks imported per minute",
     "measurement": "http",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "meter" },
      { "condition": "AND", "key": "api_endpoint", "operator": "=", "value": "blocks" }
     ]
    }
   ]
  }
 ]
}