{
 "title": "xDAI Project",
 "tags": [ "project" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "xdai validator CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 +100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "xdai-validator" }
     ]
    }
   ]
  },
  {
   "title": "xdai validator Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "xdai-validator" }
     ]
    }
   ]
  },
  {
   "title": "xdai validator Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "/ volume",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "xdai-validator" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "xdai validator - PARITY container is listening on :8545",
   "type": "graph",
   "description": "0 - up to date\n\nno data - syncing",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "api_method", "operator": "=", "value": "eth_syncing" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "xdai-validator" }
     ]
    }
   ]
  },
  {
   "title": "xdai validator Highest Block Number",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "api_method", "operator": "=", "value": "eth_blocknumber" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "xdai-validator" }
     ]
    }
   ]
  },
  {
   "title": "xdai validator Highest Block Number growth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "blocks pere minute",
     "measurement": "exec",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "api_method", "operator": "=", "value": "eth_blocknumber" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "xdai-validator" }
     ]
    }
   ]
  },
  {
   "title": "xdai validator Containers Running Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "xdai-validator" }
     ]
    }
   ]
  },
  {
   "title": "xDAI Bridge Balance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "xDAI" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "xDAI",
     "measurement": "exec",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "xdai-validator" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_getbalance" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "bridge" }
     ]
    }
   ]
  },
  {
   "title": "xDAI Bridge Balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "xDAI" }
   ],
   "targets": [
    {
     "alias": "xDAI Bridge Balance",
     "measurement": "exec",
     "select": [
      [
       { "params": [ "fixed_result" ], "type": "field" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "xdai-validator" },
      { "condition": "AND", "key": "api_method", "operator": "=", "value": "eth_getbalance" },
      { "condition": "AND", "key": "address", "operator": "=", "value": "bridge" }
     ]
    }
   ]
  }
 ]
}