{
 "title": "BNB node 1",
 "tags": [ "node" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "BNB-node-1 CPU Utilization",
   "type": "graph",
   "description": "Average CPU utilization on the node",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0012b8966e2ea5eea" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "BNB-node-1 Memory Utilization",
   "type": "graph",
   "description": "Average memory utilization on the node",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0012b8966e2ea5eea" },
     "metricName": "mem_used_percent",
     "namespace": "BNB/CWAgent",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "BNB-node-1 Disk Utilization",
   "type": "graph",
   "description": "Disk usage. Green line shows the current usage, yellow and red - the alert thresholds.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0012b8966e2ea5eea" },
     "metricName": "disk_used_percent",
     "namespace": "BNB/CWAgent",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "BNB-node-1 Health Status",
   "type": "graph",
   "description": "Reports whether the instance has passed both the instance status check and the system status check in the last minute. This metric can be either 0 (passed) or 1 (failed)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0012b8966e2ea5eea" },
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "region": "us-east-2",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}