{
 "title": "ETH Archive node",
 "tags": [ "node" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "CPU utilization",
   "type": "graph",
   "description": "Average CPU utilization",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0225d12535c0caa74" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "description": "Average RAM utilization",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0225d12535c0caa74" },
     "metricName": "mem_used_percent",
     "namespace": "ETH/CWAgent",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "description": "Average disk utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0225d12535c0caa74", "path": "/" },
     "metricName": "disk_used_percent",
     "namespace": "ETH/CWAgent",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "InstanceId": "i-0225d12535c0caa74", "path": "/data" },
     "metricName": "disk_used_percent",
     "namespace": "ETH/CWAgent",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Free space on /data",
   "type": "graph",
   "description": "Free space on /data volume where all the blockchain data is stored",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0225d12535c0caa74", "path": "/data" },
     "metricName": "disk_free",
     "namespace": "ETH/CWAgent",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Failed Status Checks",
   "type": "graph",
   "description": "Reports whether the instance has passed both the instance status check and the system status check in the last minute. This metric can be either 0 (passed) or 1 (failed)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0225d12535c0caa74" },
     "metricName": "StatusCheckFailed_Instance",
     "namespace": "AWS/EC2",
     "period": "5m",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    },
    {
     "dimensions": { "InstanceId": "i-0225d12535c0caa74" },
     "metricName": "StatusCheckFailed_System",
     "namespace": "AWS/EC2",
     "period": "5m",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "PostgreSQL - Database Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "The amount of CPU being used for a DB instance",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "eth1p-armanino-eth" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "graph",
   "description": "The amount of available random access memory",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "eth1p-armanino-eth" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Storage Utilization",
   "type": "graph",
   "description": "The amount of available storage space",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "eth1p-armanino-eth" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "description": "The average number of disk write I/O operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "eth1p-armanino-eth" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "description": "The average number of disk read I/O operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "eth1p-armanino-eth" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}