{
 "title": "Tron node",
 "tags": [ "node" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "CPU utilization",
   "type": "graph",
   "description": "Average CPU utilization",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU utilization mean",
     "dimensions": { "InstanceId": "i-0457e227e5fb20627" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "description": "Average RAM utilization",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory utilization mean",
     "dimensions": { "InstanceId": "i-0457e227e5fb20627" },
     "metricName": "mem_used_percent",
     "namespace": "Tron/CWAgent",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "description": "Average disk utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0457e227e5fb20627", "path": "/" },
     "metricName": "disk_used_percent",
     "namespace": "Tron/CWAgent",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Failed Status Checks",
   "type": "graph",
   "description": "Reports whether the instance has passed both the instance status check and the system status check in the last minute. This metric can be either 0 (passed) or 1 (failed)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0457e227e5fb20627" },
     "metricName": "StatusCheckFailed_Instance",
     "namespace": "AWS/EC2",
     "period": "5m",
     "region": "us-east-2",
     "statistics": [ "Sum" ]
    },
    {
     "dimensions": { "InstanceId": "i-0457e227e5fb20627" },
     "metricName": "StatusCheckFailed_System",
     "namespace": "AWS/EC2",
     "period": "5m",
     "region": "us-east-2",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}